# Generated by Django 2.2.6 on 2019-11-05 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=1)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
